version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USERNAME: 
      POSTGRES_PASSWORD: "docker"
    ports:
      - "5432:5432"
    volumes:
      - /home/roney/Desktop/OSF/DB:/var/lib/postgresql/data 
    networks:
      - db-network
      
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres"
      PGADMIN_DEFAULT_PASSWORD: "docker"
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - db-network

networks: 
  db-network:
    driver: bridge